; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = modA1, modA2, modB1, modB2

[env]
platform = teensy
board = teensy40
framework = arduino
lib_deps =
board_build.f_cpu = 24000000   ;set clock speed in Hz
build_flags = -D MODULE_ADDRESS=0x09
monitor_speed = 115200 
#extra_scripts = wait.py

#[env:devel]

[env:debug]
build_flags = -D MODULE_ADDRESS=0x08 -D DEBUG_OUTPUT
build_type = debug
[env:modA1]
build_flags = -D MODULE_ADDRESS=0x08
build_type = release
extra_scripts =
  post:wait.py
[env:modA2]
build_flags = -D MODULE_ADDRESS=0x09
build_type = release
extra_scripts =
  post:wait.py
[env:modB1]
build_flags = -D MODULE_ADDRESS=0x0A
build_type = release
extra_scripts =
  post:wait.py
[env:modB2]
build_flags = -D MODULE_ADDRESS=0x0B
build_type = release
extra_scripts =
  post:wait.py

; [env:modC1]
; build_flags = -D MODULE_ADDRESS=0x0C
; build_type = release
; extra_scripts =
;   post:wait.py

; [env:modC2]
; build_flags = -D MODULE_ADDRESS=0x0D
; build_type = release
; extra_scripts =
;   post:wait.py